"""prax.store — the only module that touches SQLite.

Everything else (the door, the MCP proxy, the importers, the one-off
scripts) calls these functions: ingest in two steps (``register``,
``index_text``), search, the graph, pages, jobs. It was one file until it
passed four thousand lines; it is a package now, one module per concern,
and the surface is unchanged — everything is still ``store.<name>`` and
every module re-exports here.

Concurrency: the door runs sync handlers on worker threads, so connections
are created with ``check_same_thread=False``, reads take a connection per
thread (``thread_connection``) and every write is serialized behind one
process-wide re-entrant lock (invariant 4).

| module | what lives there |
|---|---|
| ``base`` | the connection, the lock, the archive, the index files |
| ``documents`` | ingest, read, meta, domains, promotion, retiring |
| ``retrieval`` | query expansion, FTS, vectors, fusion, rerank |
| ``graph`` | entities, edges, traversal, the review queue |
| ``pages`` | the notes that are documents too |
| ``jobs`` | what runs and what ran |
| ``summary`` | what the store holds, counted |
| ``repair`` | the damage that recurs: `health` finds it, `heal` mends it |
| ``backup`` | a copy of the store somewhere else, incrementally |
"""

from __future__ import annotations

import json  # noqa: F401 - store.json is part of the surface
import sqlite3  # noqa: F401 - callers type against store.sqlite3

from prax import chunking, config, embeddings, ontology, vectors  # noqa: F401
from prax import rerank as rerank_mod  # noqa: F401

from .backup import (  # noqa: F401
    MANIFEST,
    backup,
    backup_target,
)
from .base import (  # noqa: F401
    _LOCK,
    _NOW,
    _SURROGATE,
    _TOKEN,
    BUSY_TIMEOUT,
    LOCK_RETRIES,
    VEC_DIM,
    P,
    R,
    _archive_bytes,
    _archive_path,
    _delta,
    _delta_path,
    _depth,
    _doc_index,
    _doc_index_path,
    _drop_index_views,
    _drop_legacy_vec_table,
    _get_vector,
    _has_vectors,
    _index,
    _index_path,
    _indexes,
    _knn,
    _like_prefix,
    _local,
    _open_index,
    _read_archive,
    _serialized,
    connect,
    init_db,
    migrations,
    schema_version,
    sha256_file,
    thread_connection,
    vectors_available,
)
from .documents import (  # noqa: F401
    _KIND_WORDS,
    DOCTYPES,
    DUPLICATE_THRESHOLD,
    MODES,
    PROMOTE_WEIGHTS,
    READINGS,
    _check_domains,
    _chunk_shape,
    _is_indexed,
    _refresh_document_field,
    _rule_matches,
    _set_promote,
    _write_chunks,
    add_domain,
    assign_domains,
    cancel_reading,
    capture_rank,
    check_mode,
    chunk_fingerprint,
    dedupe_captures,
    document_domains,
    document_field,
    document_outline,
    document_titles,
    documents_in_domain,
    expected_version,
    extracted_by,
    find_chunk,
    fingerprint_text,
    finish_reading,
    get_chunk,
    get_document,
    get_meta,
    get_original,
    index_text,
    ingest_file,
    ingest_text,
    is_indexed,
    is_retired,
    list_chunks,
    list_documents,
    live_captures_of,
    meta_index,
    note_recapture,
    original_info,
    promote,
    promoted_documents,
    promotion_candidates,
    read_chunks,
    reading_requests,
    rechunk,
    refresh_document_fields,
    register,
    remove_domain,
    request_reading,
    request_readings,
    restamp_ontology,
    retire_document,
    retitle,
    select_documents,
    select_for_reading,
    set_domains,
    set_meta,
    set_text_source,
    similarity,
    text_unchanged,
    unpromote,
    unreadable_documents,
    unretire_document,
)
from .graph import (  # noqa: F401
    ASK_FACT_RELS_SKIPPED,
    CONFIDENCE_LEVELS,
    HUB_TYPES,
    MAX_HOPS,
    Edge,
    _doc_ids_by_title,
    _docs_by_zotero_key,
    _entity_id,
    _review_where,
    _subset_version_case,
    backfill_provenance,
    canonical_entity,
    count_review,
    document_context,
    document_facts,
    find_edges,
    find_entities,
    get_review,
    hub_graph,
    invalidate_edge,
    link,
    list_review,
    merge_entities,
    provenance_summary,
    queue_review,
    resolve_review,
    resolve_review_many,
    retire_reading,
    retire_run,
    retype_review,
    select_for_extraction,
    traverse,
)
from .jobs import (  # noqa: F401
    JOB_DEAD_SECONDS,
    JOB_STALE_SECONDS,
    Job,
    _job_now,
    _pid_alive,
    data_version,
    get_job,
    job_finish,
    job_reap,
    job_start,
    job_update,
    list_jobs,
    release_vector_views,
    running_jobs,
)
from .maintain import (  # noqa: F401
    ON_REQUEST,
    PASSES,
    maintain,
)
from .pages import (  # noqa: F401
    _SLUG_CHARS,
    PAGE_AUTHORS,
    PAGE_KINDS,
    _page_original,
    add_to_project,
    append_page,
    get_page,
    list_pages,
    page_revision_text,
    page_titles,
    slugify,
    write_page,
)
from .repair import (  # noqa: F401
    AILMENTS,
    PLACEHOLDER_NAMES,
    Ailment,
    clean_name,
    heal,
    health,
)
from .retrieval import (  # noqa: F401
    ACRONYM_EXPANSIONS,
    ACRONYM_MIN_DOCS,
    ALL_TERMS_WEIGHT,
    CENTROID_CHUNKS,
    CENTROID_MIN_CHARS,
    CONTEXT_LIMIT,
    DELTA_MERGE_AT,
    FIELD_WEIGHT,
    FIELD_WEIGHT_WORDS,
    RARE_CHUNKS,
    RARE_MAX_LEN,
    RARE_TERMS_WEIGHT,
    RERANK_DEPTH,
    RRF_DEPTH,
    RRF_K,
    SEARCH_MODES,
    VEC_EXPAND,
    VEC_SEARCH_CAP,
    _apply_rerank,
    _expr,
    _field_fts_search,
    _field_hit,
    _field_vec_search,
    _field_weight,
    _fill_chunks,
    _filter_doctype,
    _filter_domain,
    _finish,
    _fts_query,
    _fts_search,
    _fts_snippets,
    _merge,
    _rare_terms,
    _rrf,
    _save_delta,
    _search_hits,
    _similar_documents,
    _vec_count,
    _vec_search,
    acronym_expansions,
    compact_vectors,
    count_pending_document_embeddings,
    count_pending_embeddings,
    delta_counts,
    expand_query,
    expanded_text,
    merge_vectors,
    pending_document_embeddings,
    pending_embeddings,
    replace_acronyms,
    save_document_vectors,
    save_vectors,
    search,
    similar_documents,
    store_document_embeddings,
    store_embeddings,
    vec_status,
)
from .summary import (  # noqa: F401
    stats,
)
