"""The graph: entities, edges as evidence, and the review queue.

Edges carry their provenance and are invalidated, never deleted (invariant
8); every triple is validated against the composed ontology (invariant 9)
and a misfit goes to the review queue instead of into the graph. Traversal
walks canonical ids, so a merged alias and its survivor are one node.

A package of parts, each importing only from the ones before it in
``ORDER``; this module re-exports every name, so a caller outside writes
``from .graph import name`` as before."""

from __future__ import annotations

ORDER = (
    "edges",
    "decisions",
    "labels",
    "languages",
    "context",
    "communities",
    "traversal",
)

from .communities import (  # noqa: F401
    CARRY,
    FRESH,
    LIST_MEMBERS,
    PART_SHARE,
    REGION_HITS,
    REGION_MEMBERS,
    REGION_PLACED,
    REGION_PLACED_MIN,
    REGION_SHARE,
    SUMMARY_MIN,
    _members,
    _summary_state,
    communities_input,
    communities_to_summarize,
    community,
    community_of,
    jaccard,
    list_communities,
    regions_for_matching,
    regions_of,
    replace_communities,
    set_community_summary,
)
from .context import (  # noqa: F401
    _CONFIDENCE_BY_RANK,
    _SUBGRAPH_EDGE,
    ASK_FACT_RELS_SKIPPED,
    DOCUMENT_EDGES,
    HUB_TYPES,
    IDENTITY_META,
    MERGE_TYPES,
    SPELLING,
    _doc_ids_by_title,
    _docs_by_zotero_key,
    _sides,
    _suspect,
    candidates_page,
    described_devices,
    document_context,
    document_edges,
    document_facts,
    document_identities,
    documents_as_pages,
    documents_by_hash,
    documents_sharing,
    entities_of_documents,
    entity_answering,
    entity_named_in,
    hub_graph,
    labels_of_entities,
    merges_page,
    own_type,
    page_slugs_of,
    seed_documents,
    subgraph_edges,
)
from .decisions import (  # noqa: F401
    _review_where,
    candidate_runs,
    count_review,
    decide_candidates,
    entity_candidates,
    get_review,
    list_review,
    queue_review,
    replace_entity_candidates,
    resolve_review,
    resolve_review_many,
    retype_review,
    score_candidates,
    scored_pairs,
)
from .edges import (  # noqa: F401
    CONFIDENCE_LEVELS,
    Edge,
    _entity_id,
    _said_openly,
    _subset_version_case,
    backfill_provenance,
    canonical_entity,
    entities_with_degree,
    entity_name,
    find_edges,
    find_entities,
    invalidate_edge,
    link,
    provenance_summary,
    retire_reading,
    retire_run,
    select_for_extraction,
)
from .labels import (  # noqa: F401
    PERSON,
    PRINTED_MAX,
    SPLIT,
    _display_name,
    _label_from_merge,
    _record_pair,
    _refresh_name,
    add_label,
    decide_pair,
    display_language,
    entities_by_label,
    entity_labels,
    entity_names,
    keep_printed,
    merge_entities,
    rename_display_language,
    rename_entity,
    undecide_pair,
    unmerge_entity,
    unmerge_run,
)
from .languages import (  # noqa: F401
    _ENTITY_DOCS,
    _NAME_WORD,
    LABEL_WORDS,
    NAME_MAX_WORDS,
    _mark_corpus_ruling,
    _named_by_language,
    corpus_rulings,
    foreign_names,
    in_english_text,
    label_in_language,
    languages_by_entity,
    library_sizes,
    name_in_english,
    unlabelled_names,
    unmark_corpus_ruling,
)
from .traversal import (  # noqa: F401
    EDGES,
    MAX_HOPS,
    MIN_DOCUMENTS,
    NEIGHBOURS,
    PER_TYPE,
    _choose,
    _domain_documents,
    _first_hop,
    _kinds,
    _neighbourhood_limits,
    _second_hop,
    _walk,
    senses,
    traverse,
    traverse_map,
)
